name: Run Craft Commands

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Craft environment and run Craft command
      run: |
        source /home/kolf/CraftRoot/craft/craftenv.sh && cs kolf && git pull && craft --package kolf
    - uses: actions/upload-artifact@v4
      with:
        name: kolf-build-latest-appImage
        path: path/to/artifact/world.txt
